# Generated by Django 4.1.5 on 2023-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='receipes')),
                ('ingredients', models.CharField(max_length=500)),
                ('procedure', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
