# Generated by Django 4.1.5 on 2023-01-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0003_alter_receipes_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipes',
            name='container',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
