# Generated by Django 4.1.5 on 2023-01-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0004_receipes_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipes',
            name='container',
            field=models.IntegerField(null=True),
        ),
    ]
