# Generated by Django 4.1.5 on 2023-01-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0005_alter_receipes_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipes',
            name='container',
        ),
        migrations.RemoveField(
            model_name='receipes',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='receipes',
            name='procedure',
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.IntegerField(null=True)),
                ('ingredients', models.CharField(max_length=500)),
                ('procedure', models.CharField(max_length=1000)),
                ('receipes', models.ManyToManyField(blank=True, related_name='container', to='rec_app.receipes')),
            ],
        ),
    ]
