# Generated by Django 4.1.5 on 2023-01-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0006_remove_receipes_container_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='container',
        ),
        migrations.RemoveField(
            model_name='container',
            name='receipes',
        ),
        migrations.AddField(
            model_name='container',
            name='receipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rec_app.receipes'),
        ),
    ]
