# Generated by Django 4.1.5 on 2023-01-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_app', '0007_remove_container_container_remove_container_receipes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='receipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='rec_app.receipes'),
        ),
    ]
